Improve error handling

diff --git a/task/sast-crypto-scan/sast-crypto-scan.yaml b/task/sast-crypto-scan/sast-crypto-scan.yaml
--- a/task/sast-crypto-scan/sast-crypto-scan.yaml
+++ b/task/sast-crypto-scan/sast-crypto-scan.yaml
@@ -76,18 +76,20 @@ spec:
         #!/usr/bin/env bash
         set -euo pipefail
 
-        CONSOLE=$(oc whoami --show-console | sed -E 's|^https://console-openshift-console\.apps\.([^.:]*)\..*:?.*$|\1|')
-        echo "Running on: $CONSOLE"
+        CLUSTER=$(oc whoami --show-console | sed -E 's|^https://console-openshift-console\.apps\.([^.:]*)\..*:?.*$|\1|')
+        echo "Running on: $CLUSTER"
 
         # This unpinned image contain the latest rolling version of the rules
         IMAGE="crypto-rules-image:latest"
 
         # There are two ways of accessing the proprietary crypto-rules-image depending on the cluster
-        if [[ "${CONSOLE}" =~ ^(kflux-prd-rh03|kflux-prd-rh02|kflux-prd-rh01|stone-prod-p02|stone-prod-p01|kflux-ocp-p01|kflux-rhel-p01|kflux-osp-p01|stone-stg-rh01)$ ]] ; then
+        if [[ "${CLUSTER}" =~ ^(kflux-prd-rh03|kflux-prd-rh02|kflux-prd-rh01|stone-prod-p02|stone-prod-p01|kflux-ocp-p01|kflux-rhel-p01|kflux-osp-p01|stone-stg-rh01)$ ]] ; then
+          echo "Using image from quay.io using robot federated account"
           # Use bounded token with quay.io federated robot account
           ADDITIONAL_RULES_IMAGE="quay.io/exd-guild-security/${IMAGE}"
           ROBOT_ACCOUNT="exd-guild-security+konflux_crypto_rules_pull"
-        elif [[ "${CONSOLE}" =~ ^(stone-stage-p01)$ ]] ; then
+        elif [[ "${CLUSTER}" =~ ^(stone-stage-p01)$ ]] ; then
+          echo "Using image from internal openshift registry"
           # Use internal mirrored image
           ADDITIONAL_RULES_IMAGE="image-registry.openshift-image-registry.svc:5000/tmp-sguarino/${IMAGE}"
           ROBOT_ACCOUNT=""
@@ -107,10 +109,12 @@ spec:
             exit 1
           fi
 
+          set +e
           SL_TOKEN=$(curl -s --fail \
             --user "${ROBOT_ACCOUNT}:${TOKEN}" \
             "https://${REGISTRY_HOSTNAME}/oauth2/federation/robot/token" \
-            | python3 -c 'import json,sys;print(json.load(sys.stdin)["token"])')
+            | python3 -c 'import json,sys;print(json.load(sys.stdin)["token"])' 2> /dev/null)
+          set -e
 
           if [ -n "${SL_TOKEN}" ] ; then
             export XDG_RUNTIME_DIR=/tmp/oc-run
@@ -119,6 +123,8 @@ spec:
           else
             echo "WARNING: Unable to authenticate to $REGISTRY_HOSTNAME with $ROBOT_ACCOUNT and bound token"
             echo "Falling back to use only Open Source Rules"
+            TEST_OUTPUT=$(echo "{\"result\":\"SUCCESS\",\"timestamp\":\"$(date -u --iso-8601=seconds)\",\"failures\":0,\"successes\":0,\"warnings\":1}")
+            echo "${TEST_OUTPUT}" | tee "$(results.TEST_OUTPUT.path)"
             exit 0
           fi
         fi
@@ -184,6 +190,7 @@ spec:
           fi
         done
 
+        WARNINGS=0
         if [ "${SKIP_SBOM_GENERATION}" != "false" ]; then
           RESULT="SKIPPED"
           SUCCESSES="0"
@@ -197,6 +204,10 @@ spec:
           RESULT="SUCCESS"
           SUCCESSES="1"
           FAILURES="0"
+          if [ -f $(results.TEST_OUTPUT.path) ]; then
+            WARNINGS=$(sed -e 's/^.*warnings":\([[:digit:]]*\).*$/\1/p;d' $(results.TEST_OUTPUT.path))
+            RESULT="WARNING"
+          fi
           echo "Running crypto scanner on the specified targets"
           crypto-finder \
             scan \
@@ -206,9 +217,8 @@ spec:
             --timeout "${SCAN_TIMEOUT}" \
             "${ALL_TARGETS[@]}" > "${OUTPUT_FILE}"
         fi
-        TEST_OUTPUT=$(echo "{\"result\":\"${RESULT}\",\"timestamp\":\"$(date -u --iso-8601=seconds)\",\"failures\":${FAILURES},\"successes\":${SUCCESSES},\"warnings\":0}")
+        TEST_OUTPUT=$(echo "{\"result\":\"${RESULT}\",\"timestamp\":\"$(date -u --iso-8601=seconds)\",\"failures\":${FAILURES},\"successes\":${SUCCESSES},\"warnings\":${WARNINGS}}")
         echo "${TEST_OUTPUT}" | tee "$(results.TEST_OUTPUT.path)"
-        echo "Task $(context.task.name) completed."
       computeResources:
         limits:
           cpu: "8"
@@ -265,6 +275,7 @@ spec:
             exit 1
           fi
         done
+        echo "Task $(context.task.name) completed."
       computeResources:
         limits:
           memory: 256Mi
